---
- name: Download Rust installer.
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh

- name: Set executable flag for Rust installer.
  file:
    path: /tmp/rustup.sh
    mode: a=rx

- name: Install Rust.
  command: sh /tmp/rustup.sh -y

- name: Clean up Rust installer.
  file:
    path: /tmp/rustup.sh
    state: absent

- name: Add Rust to PATH.
  template:
    src: "templates/rust.fish.j2"
    dest: "{{ fish_config_directory }}/rust.fish"
  when: fish_config_directory is defined
