---
- name: Install the Rust toolchain installer.
  community.general.homebrew:
    name: rustup-init
    state: present

- name: Check if Rust is already installed.
  ansible.builtin.stat:
    path: "{{ ansible_env['HOME'] }}/.cargo/bin/cargo"
  register: cargo

- name: Install the latest Rust stable toolchain.
  ansible.builtin.command: rustup-init -y -c cargo rustfmt clippy
  register: rustup_init
  when: not cargo.stat.exists
  changed_when: rustup_init.rc == 0

- name: Add Rust to the PATH
  ansible.builtin.copy:
    src: "rust.zsh"
    dest: "{{ shell_zsh_config_dir }}/rust.zsh"
    mode: "0644"
