---

- name: Discover location of fish executable.
  command: which fish
  register: fish
  changed_when: "'fish' in fish.stdout"

- name: Change default shell.
  user:
    name: "{{ ansible_user }}"
    shell: "{{ fish.stdout }}"
  become: "yes"

- name: Ensure fish directory exists.
  file:
    path: "{{ fish_directory }}"
    owner: "{{ ansible_user_id }}"
    state: directory
    mode: 0700

- name: Ensure fish config file exists.
  file:
    path: "{{ fish_directory }}/config.fish"
    owner: "{{ ansible_user_id }}"
    state: touch
    mode: 0700

- name: Ensure fish config directory exists.
  file:
    path: "{{ fish_config_directory }}"
    owner: "{{ ansible_user_id }}"
    state: directory
    mode: 0700

- name: Ensure fish functions directory exists.
  file:
    path: "{{ fish_functions_directory }}"
    owner: "{{ ansible_user_id }}"
    state: directory
    mode: 0700

- name: Install fisher package manager.
  get_url:
    url: https://git.io/fisher
    dest: "{{ fish_functions_directory }}/fisher.fish"

- name: Install fish-ssh-agent package.
  shell: fisher add danhper/fish-ssh-agent
  args:
    executable: "{{ fish.stdout }}"

- name: Copy functions.
  template:
    src: "{{ item }}"
    dest: "{{ fish_functions_directory }}/{{ item | basename | regex_replace('.j2', '') }}"
  with_fileglob:
    - "templates/*.j2"
