---

- include_tasks: macos.yml
  when: ansible_os_family == 'Darwin'
  tags:
    - desktop
    - package
    - terminal

- include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
  tags:
    - desktop
    - package
    - terminal
