---
- name: Install zsh.
  homebrew:
    name: zsh
    state: present

- name: Install syntax highlighting for zsh.
  homebrew:
    name: zsh-syntax-highlighting
    state: present

- name: Install completions for zsh.
  homebrew:
    name: zsh-completions
    state: present

- name: Install coreutils.
  homebrew:
    name: coreutils
    state: present

- name: Discover location of zsh executable.
  ansible.builtin.command: which zsh
  register: zsh
  changed_when: false

- name: Change default shell.
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh.stdout }}"
  become: true

- name: Create zsh configuration directory.
  ansible.builtin.file:
    path: "{{ zsh_config_dir }}"
    owner: "{{ ansible_user_id }}"
    state: directory
    mode: 0700

- name: Copy zshenv.
  ansible.builtin.template:
    src: zshenv.j2
    dest: "{{ ansible_env['HOME'] }}/.zshenv"
    mode: 0644

- name: Copy zshrc.
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ zsh_config_dir }}/.zshrc"
    mode: 0644

- name: Copy zsh aliases.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ zsh_config_dir }}/{{ item | basename }}"
    mode: 0644
  with_fileglob:
    - "files/*.zsh"
