---
- name: Tap cask-drivers repository.
  community.general.homebrew_tap:
    name: homebrew/cask-drivers
    state: present

- name: Install applications through Homebrew.
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ formulae }}"

- name: Install applications through Homebrew Cask.
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ casks }}"

- name: Install applications from Mac App Store.
  ansible.builtin.import_role:
    name: geerlingguy.mac.mas
  vars:
    mas_installed_apps: "{{ mac_store_apps }}"
