---
- name: Tap cask-drivers repository.
  community.general.homebrew_tap:
    name: homebrew/cask-drivers
    state: present

- name: Install applications through Homebrew.
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ formulae }}"

- name: Install applications through Homebrew Cask.
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ casks }}"

- name: Install applications from Mac App Store.
  ansible.builtin.import_role:
    name: geerlingguy.mac.mas
  vars:
    mas_installed_apps: "{{ apps }}"

# Workaround for https://github.com/kcrawford/dockutil/issues/127
- name: Tap repository for dockutil.
  community.general.homebrew_tap:
    name: hpedrorodrigues/tools
    state: present

- name: Install a version of dockutil that supports Monterey.
  community.general.homebrew_cask:
    name: dockutil
    state: present

- name: Configure the Dock.
  ansible.builtin.import_role:
    name: geerlingguy.mac.dock
  vars:
    dockitems_remove: # noqa var-naming[no-role-prefix]
      - Launchpad
      - Safari
      - Mail
      - Maps
      - Photos
      - Contacts
      - Reminders
      - Notes
      - TV
      - Music
      - Podcasts
      - Keynote
      - Pages
      - Numbers
      - App Store
      - TextEdit
      - News

    dockitems_persist: "{{ dock_items }}" # noqa var-naming[no-role-prefix]
