---
- hosts: all
  connection: local

  roles:
    # Set up tooling
    - { role: homebrew, tags: ["base"] }
    - { role: ansible, tags: ["base"] }

    # Configure terminal applications
    - { role: ssh, tags: ["terminal"] }
    - { role: shell, tags: ["terminal"] }
    - { role: neovim, tags: ["terminal"] }
    - { role: git, tags: ["terminal", "dev"] }

    # Install programming languages and tools
    - role: aws
      when: '"aws" in stacks'
      tags: ["terminal", "dev", "aws"]

    - role: php
      when: '"php" in stacks'
      tags: ["terminal", "dev", "php"]

    - role: python
      when: '"python" in stacks'
      tags: ["terminal", "dev", "python"]

    - role: ruby
      when: '"ruby" in stacks'
      tags: ["terminal", "dev", "ruby"]

    - role: rust
      when: '"rust" in stacks'
      tags: ["terminal", "dev", "rust"]

    - role: packer
      when: '"packer" in stacks'
      tags: ["terminal", "dev", "packer"]

    - role: terraform
      when: '"terraform" in stacks'
      tags: ["terminal", "dev", "terraform"]

    # Install applications
    - { role: software, tags: ["workstation"] }
    - role: work_e
      when: '"rust" in stacks'
      tags: ["terminal", "workstation", "rust"]

  tasks:
    - name: Manage Git repositories
      ansible.builtin.include_role:
        name: repository
      tags: ["terminal", "workstation", "dev"]
      vars:
        project: "{{ project_item }}"
      loop_control:
        loop_var: project_item
      loop: "{{ repositories }}"
