---
- hosts: localhost
  connection: local

  roles:
    # Set up tooling
    - { role: geerlingguy.mac.homebrew, tags: ["base"] }

    # Set up Ansible
    - { role: ansible, tags: ["base"] }

    # Configure terminal applications
    - { role: ssh, tags: ["base", "terminal"] }
    - { role: shell, tags: ["base", "terminal"] }
    - { role: neovim, tags: ["base", "terminal"] }
    - { role: git, tags: ["base", "terminal", "dev"] }

    # Install programming languages and tools
    - { role: aws, tags: ["terminal", "dev"] }
    - { role: php, tags: ["terminal", "dev"] }
    - { role: python, tags: ["terminal", "dev", "python"] }
    - { role: ruby, tags: ["terminal", "dev", "ruby"] }
    - { role: rust, tags: ["terminal", "dev"] }
    - { role: terraform, tags: ["terminal", "dev"] }

    # Install applications
    - { role: software, tags: ["workstation"] }

  tasks:
    - name: Manage Git repositories
      ansible.builtin.include_role:
        name: repository
      tags: ["terminal", "workstation", "dev"]
      vars:
        project: "{{ project_item }}"
      loop_control:
        loop_var: project_item
      loop: "{{ repositories }}"
