---
- name: Tap aws repository.
  community.general.homebrew_tap:
    name: aws/tap
    state: present

- name: Install the AWS CLI.
  homebrew:
    name: awscli
    state: present

- name: Ensure AWS config directory exists.
  ansible.builtin.file:
    path: "{{ aws_config_directory }}"
    owner: "{{ ansible_user_id }}"
    state: directory
    mode: 0700

- name: Copy AWS CLI configuration.
  ansible.builtin.copy:
    src: "config"
    dest: "{{ aws_config_directory }}/config"
    mode: 0600

- name: Print the 1Password vault from which to retrieve AWS credentials.
  ansible.builtin.debug:
    msg: "1Password vault: {{ onepassword_vault }}"

- name: Configure credentials.
  ansible.builtin.template:
    src: credentials.j2
    dest: "{{ aws_config_directory }}/credentials"
    mode: 0600
