---
- name: Tap aws repository.
  community.general.homebrew_tap:
    name: aws/tap
    state: present

- name: Install the AWS CLI.
  homebrew:
    name: awscli
    state: present

- name: Install the SAM CLI.
  homebrew:
    name: aws-sam-cli
    state: present

- name: Copy AWS CLI configuration.
  ansible.builtin.copy:
    src: "config"
    dest: "{{ ansible_env['HOME'] }}/.aws/config"
    mode: 0600

- name: Configure credentials.
  ansible.builtin.template:
    src: credentials.j2
    dest: "{{ ansible_env['HOME'] }}/.aws/credentials"
    mode: 0600
