---
- name: Create directory for owner.
  ansible.builtin.file:
    path: "{{ ansible_env['HOME'] }}/Developer/{{ repository_project.repo.owner }}"
    state: directory
    mode: 0755
  register: owner_directory

- name: Create directory for repository.
  ansible.builtin.file:
    path: "{{ owner_directory.path }}/{{ repository_project.repo.name }}"
    state: directory
    mode: 0755
  register: repo_directory

- name: Clone Git repository.
  ansible.builtin.git:
    repo: "git@github.com:{{ repository_project.repo.owner }}/{{ repository_project.repo.name }}.git"
    dest: "{{ repo_directory.path }}"
  register: git_clone_result
  ignore_errors: true

- name: Configure Git user email.
  community.general.git_config:
    scope: local
    repo: "{{ repo_directory.path }}"
    name: user.email
    value: "{{ repository_project.user.email }}"
  when: project.user.email is defined and project.user.email != ""

- name: Configure PGP signing key.
  community.general.git_config:
    scope: local
    repo: "{{ repo_directory.path }}"
    name: user.signingkey
    value: "{{ repository_project.user.signing_key }}"
  when: project.user.signing_key is defined and project.user.signing_key != ""

- name: Check if the project uses pre-commit.
  ansible.builtin.stat:
    path: "{{ repo_directory.path }}/.pre-commit-config.yaml"
  register: pre_commit_yaml

- name: Set up pre-commit.
  ansible.builtin.command:
    cmd: pre-commit install
    chdir: "{{ repo_directory.path }}"
  register: pre_commit_install
  when: pre_commit_yaml.stat.exists
  changed_when: pre_commit_install.rc == 0
  failed_when: pre_commit_install.rc != 0

- name: Check if the project uses Node.
  ansible.builtin.stat:
    path: "{{ repo_directory.path }}/package.json"
  register: package_json

- name: Install npm dependencies.
  ansible.builtin.command:
    cmd: npm install
    chdir: "{{ repo_directory.path }}"
  register: npm_install
  when: package_json.stat.exists
  changed_when: npm_install.rc == 0
  failed_when: npm_install.rc != 0

- name: Clean Node modules.
  ansible.builtin.file:
    path: "{{ repo_directory.path }}/node_modules"
    state: absent
  when: package_json.stat.exists and repository_is_archived

- name: Check if the project uses Rust.
  ansible.builtin.stat:
    path: "{{ repo_directory.path }}/Cargo.toml"
  register: cargo_toml

- name: Set up Rust toolchain.
  ansible.builtin.command:
    cmd: cargo build
    chdir: "{{ repo_directory.path }}"
  register: cargo_build
  when: cargo_toml.stat.exists
  changed_when: cargo_build.rc == 0
  failed_when: cargo_build.rc != 0

- name: Clean Rust artifacts.
  ansible.builtin.file:
    path: "{{ repo_directory.path }}/target"
    state: absent
  when: cargo_toml.stat.exists and repository_is_archived
