---
- name: Create directory for owner.
  ansible.builtin.file:
    path: "{{ ansible_env['HOME'] }}/Developer/{{ project.repo.owner }}"
    state: directory
    mode: 0755
  register: owner_directory

- name: Create directory for repository.
  ansible.builtin.file:
    path: "{{ owner_directory.path }}/{{ project.repo.name }}"
    state: directory
    mode: 0755
  register: repo_directory

- name: Clone Git repository.
  ansible.builtin.git:
    repo: "git@github.com:{{ project.repo.owner }}/{{ project.repo.name }}.git"
    dest: "{{ repo_directory.path }}"
  register: git_clone_result
  ignore_errors: true

- name: Configure default Git user email.
  git_config:
    scope: local
    repo: "{{ repo_directory.path }}"
    name: user.email
    value: "{{ project.user.email }}"
  when: project.user.email is defined and project.user.email != ""

- name: Configure default PGP signing key.
  git_config:
    scope: local
    repo: "{{ repo_directory.path }}"
    name: user.signingkey
    value: "{{ project.user.signing_key }}"
  when: project.user.signing_key is defined and project.user.signing_key != ""

- name: Check if the project uses pre-commit.
  ansible.builtin.stat:
    path: "{{ repo_directory.path }}/.pre-commit-config.yaml"
  register: pre_commit_yaml

- name: Set up pre-commit.
  ansible.builtin.command:
    cmd: pre-commit install
    chdir: "{{ repo_directory.path }}"
  when: pre_commit_yaml.stat.exists
  ignore_errors: true

- name: Check if the project uses Rust.
  ansible.builtin.stat:
    path: "{{ repo_directory.path }}/Cargo.toml"
  register: cargo_toml

- name: Set up Rust toolchain.
  ansible.builtin.command:
    cmd: cargo build
    chdir: "{{ repo_directory.path }}"
  when: cargo_toml.stat.exists
  ignore_errors: true

- name: Clean Rust artifacts.
  ansible.builtin.file:
    path: "{{ repo_directory.path }}/target"
    state: absent
  when: cargo_toml.stat.exists and archived
