---

- name: Configure Git user name.
  git_config:
    name: user.name
    scope: global
    value: "{{ git.username }}"

- name: Configure Git user email.
  git_config:
    name: user.email
    scope: global
    value: "{{ git.email }}"

- name: Create global excludes file.
  file:
    path: "{{ git_excludes_file }}"
    state: touch

- name: Set global excludes file.
  git_config:
      name: core.excludesfile
      scope: global
      value: "{{ git_excludes_file }}"

- name: Set current branch as default push target.
  git_config:
    name: push.default
    scope: global
    value: current

- name: Copy Git functions.
  template:
    src: "{{ item }}"
    dest: "{{ fish_functions_directory }}/{{ item | basename | regex_replace('.j2', '') }}"
  with_fileglob:
    - "templates/*.j2"
