---
- name: Install Git.
  community.general.homebrew:
    name: git
    state: present

- name: Create global excludes file.
  ansible.builtin.copy:
    src: gitignore_global
    dest: "{{ git_excludes_file }}"
    mode: "0644"

- name: Copy Git aliases.
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ zsh_config_dir }}/{{ item | basename }}"
    mode: "0644"
  with_fileglob:
    - "templates/*.zsh.j2"

- name: Copy Git configuration.
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ ansible_env['HOME'] }}/.gitconfig"
    mode: "0644"

- name: Remove git alias.
  ansible.builtin.file:
    path: "{{ zsh_config_dir }}/git.zsh"
    state: absent
