---

- include: macos.yml
  when: ansible_os_family == 'Darwin'
  tags:
    - desktop
    - git
    - terminal

- include: ubuntu.yml
  when: ansible_os_family == 'Debian'
  tags:
    - desktop
    - git
    - terminal

- include: config.yml
  tags:
    - desktop
    - git
    - terminal
