---
- name: Install Git.
  homebrew:
    name: git
    state: present

- name: Configure default Git user name.
  git_config:
    name: user.name
    scope: global
    value: "{{ git.username }}"

- name: Configure default Git user email.
  git_config:
    name: user.email
    scope: global
    value: "{{ git.email }}"

- name: Configure default PGP signing key.
  git_config:
    name: user.signingkey
    scope: global
    value: "{{ git.signing_key }}"

- name: Configure editor for commit messages.
  git_config:
    name: core.editor
    scope: global
    value: vim

- name: Create global excludes file.
  ansible.builtin.copy:
    src: gitignore_global
    dest: "{{ git_excludes_file }}"
    mode: 0644

- name: Set global excludes file.
  git_config:
    name: core.excludesfile
    scope: global
    value: "{{ git_excludes_file }}"

- name: Enable signing commits.
  git_config:
    name: commit.gpgsign
    scope: global
    value: true

- name: Set current branch as default push target.
  git_config:
    name: push.default
    scope: global
    value: current

- name: Enable pushing tags with their associated commits.
  git_config:
    name: push.followTags
    scope: global
    value: true

- name: Copy Git aliases.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ zsh_config_dir }}/{{ item | basename }}"
    mode: 0644
  with_fileglob:
    - "files/*.zsh"
