---
- name: Install the Terraform Version Manager.
  community.general.homebrew:
    name: tfenv
    state: present

- name: Check if Terraform is installed.
  ansible.builtin.command: command -v terraform >/dev/null 2>&1
  register: terraform
  changed_when: false
  failed_when: terraform.rc != 0 and terraform.rc != 1

- name: Install the latest version of Terraform.
  ansible.builtin.command: tfenv install
  register: tfenv_install
  when: terraform.rc == 1
  changed_when: tfenv_install.rc == 0

- name: Install tflint.
  community.general.homebrew:
    name: tflint
    state: present

- name: Install tfsec.
  community.general.homebrew:
    name: tfsec
    state: present
