---
- name: Install Ansible.
  community.general.homebrew:
    name: ansible
    state: present

- name: Install ansible-lint.
  community.general.homebrew:
    name: ansible-lint
    state: present

- name: Install Python3.
  community.general.homebrew:
    name: python@3.10

- name: Install Ansible dependencies.
  ansible.builtin.pip:
    name: pexpect
    state: present
