---
- name: Install Ansible.
  community.general.homebrew:
    name: ansible
    state: present

- name: Install ansible-lint.
  community.general.homebrew:
    name: ansible-lint
    state: present

- name: Install Python3.
  community.general.homebrew:
    name: python
