---
name: Ansible

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v40
        with:
          files: |
            host_vars/**
            roles/**
            ansible.cfg
            local.yml
            requirements.yml

      - name: Print changed files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file"
          done

  lint:
    name: Lint code
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.17.0
        with:
          path: local.yml
