---
name: Ansible

"on":
  push:
    branches:
      - main
    paths:
      - "host_vars/**"
      - "roles/**"
      - "ansible.cfg"
      - "hosts"
      - "local.yml"
  pull_request:
    paths:
      - "host_vars/**"
      - "roles/**"
      - "ansible.cfg"
      - "hosts"
      - "local.yml"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    env:
      # Overwrite vault password script for tests
      ANSIBLE_VAULT_PASSWORD_FILE: vault.gpg

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.16.0
        with:
          path: local.yml
